[en]
a = "alpha"
b = "bravo"
c = "charlie"
d = "delta"
e = "echo"
f = "foxtrot"
g = "golf"
h = "hotel"
i = "india"
j = "juliett"
k = "kilo"
l = "lima"
m = "mike"
n = "november"
o = "oscar"
p = "papa"
q = "quebec"
r = "romeo"
s = "sierra"
t = "tango"
u = "uniform"
v = "victor"
w = "whiskey"
x = "x-ray"
y = "yankee"
z = "zulu"

[es]
"ñ" = "ñoñ"
a = "antonio"
b = "barcelona"
c = "carmen"
d = "dinamarca"
e = "enrique"
f = "franci"
g = "guadalupe"
h = "historia"
i = "inés"
j = "jueves"
k = "kil"
l = "lorenzo"
m = "madri"
n = "navarr"
o = "ovied"
p = "parí"
q = "queso"
r = "roma"
s = "sábado"
t = "tango"
u = "uruguay"
v = "valenci"
w = "washingto"
x = "ximena"
y = "yegu"
z = "zapata"

[it]
a = "ancona"
b = "bari"
c = "como"
d = "domodossola"
e = "empoli"
f = "firenze"
g = "genova"
h = "hotel"
i = "imola"
j = "jolly"
k = "kappa"
l = "livorno"
m = "milano"
n = "napoli"
o = "otranto"
p = "palermo"
q = "quarto"
r = "roma"
s = "savona"
t = "torino"
u = "udine"
v = "venezia"
w = "washington"
x = "xilofono"
y = "yogurt"
z = "zara"

[fr]
a = "anatole"
b = "berthe"
c = "célestin"
d = "désiré"
e = "eugène"
f = "françois"
g = "gaston"
h = "henr"
i = "irma"
j = "joseph"
k = "kléber"
l = "loui"
m = "marcel"
n = "nicolas"
o = "oscar"
p = "pierre"
q = "quintal"
r = "raoul"
s = "suzanne"
t = "thérèse"
u = "ursul"
v = "victor"
w = "william"
x = "xavie"
y = "yvonne"
z = "zo"

[de]
"ä" = "umlaut aachen"
"ö" = "umlaut offenbach"
"ß" = "eszett"
"ü" = "umlaut unna"
a = "aachen"
b = "berlin"
c = "chemnitz"
d = "düsseldorf"
e = "essen"
f = "frankfurt"
g = "goslar"
h = "hamburg"
i = "ingelheim"
j = "jena"
k = "köln"
l = "leipzig"
m = "münchen"
n = "nürnberg"
o = "offenbach"
p = "potsdam"
q = "quickborn"
r = "rostock"
s = "salzwedel"
t = "tübingen"
u = "unna"
v = "völklingen"
w = "wuppertal"
x = "xanten"
y = "ypsilon"
z = "zwickau"

[fi]
"å" = "åke"
"ä" = "äiti"
"ö" = "öljy"
a = "aarne"
b = "bertta"
c = "celsius"
d = "daavid"
e = "eemeli"
f = "farao"
g = "gideon"
h = "heikki"
i = "iivari"
j = "jussi"
k = "kalle"
l = "lauri"
m = "matti"
n = "niilo"
o = "otto"
p = "paavo"
q = "kuu"
r = "risto"
s = "sakari"
t = "tyyne"
u = "urho"
v = "vihtori"
w = "wiski"
x = "äksä"
y = "yrjö"
z = "tseta"

[se]
"å" = "åke"
"ä" = "ärlig"
"ö" = "östen"
a = "adam"
b = "bertil"
c = "cesar"
d = "david"
e = "erik"
f = "filip"
g = "gustav"
h = "helge"
i = "ivar"
j = "johan"
k = "kalle"
l = "ludvig"
m = "martin"
n = "niklas"
o = "olof"
p = "petter"
q = "qvintus"
r = "rudolf"
s = "sigurd"
t = "tore"
u = "urban"
v = "viktor"
w = "wilhelm"
x = "xerxes or kryss"
y = "yngve"
z = "zäta"

[pt]
a = "aveiro"
b = "bragança"
c = "coimbra"
d = "dafundo"
e = "évora"
f = "faro"
g = "guarda"
h = "horta"
i = "itália"
j = "josé"
k = "kilograma"
l = "lisboa"
m = "maria"
n = "nazaré"
o = "ovar"
p = "porto"
q = "queluz"
r = "rossio"
s = "setúbal"
t = "tavira"
u = "unidade"
v = "viseu"
w = "washington"
x = "xavier"
y = "york"
z = "zulmira"
